### ISSUE TITLE
Serving breaks after reload

### ISSUE THREAD

**Issue by vrugtehagel** [vrugtehagel/eleventy-document-outline#1]
When serving using 11ty's default dev server, it initially builds just fine but on subsequent builds the following error is thrown (file paths redacted):

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "../_site/…/index.html" from "./src/…/index.md" (via EleventyTemplateError)
[11ty] 2. Could not find render plugin file for the `renderFile` shortcode, looking for: tmpDirEleventyDocumentOutline/400d3ada-9143-4958-b11d-c4ae68e27505.liquid, file:./src/_includes/template.liquid, line:14, col:13 (via RenderError)
[11ty] 3. Could not find render plugin file for the `renderFile` shortcode, looking for: tmpDirEleventyDocumentOutline/400d3ada-9143-4958-b11d-c4ae68e27505.liquid (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Could not find render plugin file for the `renderFile` shortcode, looking for: tmpDirEleventyDocumentOutline/400d3ada-9143-4958-b11d-c4ae68e27505.liquid
[11ty]     at Object.compileFile (file:///…/node_modules/@11ty/eleventy/src/Plugins/RenderPlugin.js:56:9)
[11ty]     at Object._renderFileShortcodeFn (file:///…/node_modules/@11ty/eleventy/src/Plugins/RenderPlugin.js:339:30)
[11ty]     at Object.<anonymous> (file:///…/node_modules/@11ty/eleventy/src/Benchmark/BenchmarkGroup.js:35:23)
[11ty]     at Object.renderTemplate (file:///…/node_modules/@jsr/vrugtehagel__eleventy-document-outline/src/render-template.js:19:27)
[11ty]     at Object.<anonymous> (file:///…/node_modules/@jsr/vrugtehagel__eleventy-document-outline/src/index.js:69:33)
[11ty]     at Object.<anonymous> (file:///…/node_modules/@11ty/eleventy/src/Benchmark/BenchmarkGroup.js:35:23)
[11ty]     at Object.<anonymous> (file:///…/node_modules/@11ty/eleventy/src/Engines/Liquid.js:71:14)
[11ty]     at Filter.render (/…/node_modules/liquidjs/dist/liquid.node.cjs.js:2220:35)
[11ty]     at render.next (<anonymous>)
[11ty]     at toPromise (/…/node_modules/liquidjs/dist/liquid.node.cjs.js:517:32)
[11ty]     at async toPromise (/…/node_modules/liquidjs/dist/liquid.node.cjs.js:525:25)
[11ty]     at async toPromise (/…/node_modules/liquidjs/dist/liquid.node.cjs.js:525:25)
[11ty]     at async toPromise (/…/node_modules/liquidjs/dist/liquid.node.cjs.js:525:25)
[11ty]     at async TemplateLayout.renderPageEntry (file:///…/node_modules/@11ty/eleventy/src/TemplateLayout.js:225:22)
[11ty]     at async #renderPageEntryWithLayoutsAndTransforms (file:///…/node_modules/@11ty/eleventy/src/Template.js:762:14)
[11ty]     at async Template.generateMapEntry (file:///…/node_modules/@11ty/eleventy/src/Template.js:802:15)
[11ty]     at async Promise.all (index 65)
[11ty]     at async Eleventy.executeBuild (file:///…/node_modules/@11ty/eleventy/src/Eleventy.js:1296:10)
[11ty]     at async Eleventy._watch (file:///…/node_modules/@11ty/eleventy/src/Eleventy.js:894:22)
[11ty]     at async watchRun (file:///…/node_modules/@11ty/eleventy/src/Eleventy.js:1143:5)
[11ty]     at async FSWatcher.<anonymous> (file:///…/node_modules/@11ty/eleventy/src/Eleventy.js:1161:4)
```

**Comment by vrugtehagel** [comment]
Moved away from installing the `RenderPlugin` under the hood, so this issue is resolved.
